import { Company } from './types';

export const companies: Company[] = [
  {
    id: 'bicycle-therapeutics',
    name: 'Bicycle Therapeutics',
    ticker: 'BCYC',
    assetName: 'BT8009',
    isPrivate: false,
    mechanism: 'ADC',
    target: 'Nectin-4',
    stage: 'Phase 2',
    marketCap: 1.2,
    valuation: 1.2,
    nextMilestone: 'Phase 2 data readout - Q2 2025',
    validationScore: 78,
    backers: ['Atlas Venture', 'Novartis Ventures'],
    targetBiology: 'Nectin-4 is a cell adhesion molecule that plays a critical role in cell-cell interactions, particularly in epithelial tissues. It is overexpressed in various cancer types including bladder, lung, and pancreatic cancers, making it an attractive therapeutic target. The protein\'s extracellular domain mediates binding to its ligands, while its intracellular domain interacts with signaling pathways that promote cell survival and proliferation.',
    discoveryTimeline: [
      { date: '1995', event: 'Initial identification in cell adhesion studies' },
      { date: '2003', event: 'Role in cancer progression established' },
      { date: '2010', event: 'First therapeutic targeting attempts' },
      { date: '2018', event: 'Clinical validation in multiple indications' },
    ],
    structure: {
      type: 'Peptide',
      linker: 'Val-Cit',
      payload: 'MMAE',
      dar: 4,
    },
    geneticEvidence: [
      { text: 'Knockout studies show reduced tumor growth', status: 'strong', source: 'PubMed' },
      { text: 'GWAS association with disease risk', status: 'moderate', source: 'Nature Genetics' },
    ],
    clinicalPrecedent: [
      { text: 'Similar targets show clinical efficacy', status: 'strong', source: 'FDA' },
      { text: 'Phase 2 data from competitor programs', status: 'moderate', source: 'ClinicalTrials.gov' },
    ],
    biologicalRationale: [
      { text: 'Target expression correlates with patient outcomes', status: 'strong', source: 'PubMed' },
      { text: 'Mechanism of action well-characterized', status: 'strong', source: 'Cell' },
      { text: 'Limited off-target effects in preclinical models', status: 'moderate', source: 'ToxSci' },
    ],
    safetyData: {
      risks: [
        { organ: 'skin', level: 'high', notes: 'High expression in keratinocytes' },
        { organ: 'liver', level: 'medium', notes: 'Metabolic clearance pathway' },
        { organ: 'kidneys', level: 'low', notes: 'Minimal renal excretion' },
        { organ: 'lungs', level: 'medium', notes: 'Moderate target expression' },
        { organ: 'stomach', level: 'low', notes: 'Low target expression' },
        { organ: 'smallIntestine', level: 'medium', notes: 'GI tract exposure' },
        { organ: 'largeIntestine', level: 'low', notes: 'Minimal absorption' },
        { organ: 'bladder', level: 'low', notes: 'Renal clearance' },
      ],
      aeTable: [
        { event: 'Rash', allGrade: 45, grade3_4: 8, related: 'Target', comparator: 12 },
        { event: 'Fatigue', allGrade: 38, grade3_4: 5, related: 'Both', comparator: 35 },
        { event: 'Nausea', allGrade: 32, grade3_4: 3, related: 'Payload', comparator: 28 },
        { event: 'Neutropenia', allGrade: 25, grade3_4: 12, related: 'Payload', comparator: 18 },
        { event: 'Peripheral Neuropathy', allGrade: 18, grade3_4: 4, related: 'Payload', comparator: 15 },
      ],
    },
    validationMetrics: [
      {
        category: 'Genetic Evidence',
        score: 85,
        maxScore: 100,
        status: 'strong',
        details: ['Knockout studies show reduced tumor growth', 'GWAS association with disease risk'],
      },
      {
        category: 'Clinical Precedent',
        score: 78,
        maxScore: 100,
        status: 'strong',
        details: ['Similar targets show clinical efficacy', 'Phase 2 data from competitor programs'],
      },
      {
        category: 'Biological Rationale',
        score: 82,
        maxScore: 100,
        status: 'strong',
        details: ['Target expression correlates with patient outcomes', 'Mechanism of action well-characterized'],
      },
      {
        category: 'Safety Profile',
        score: 65,
        maxScore: 100,
        status: 'moderate',
        details: ['Manageable toxicity profile', 'Some organ-specific risks identified'],
      },
    ],
    sequenceData: {
      proteinSequence: 'MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEKAVQVKVKALPDAQFEVVHSLAKWKRQTLGQHDFSAGEGLYTHMKALRPDEDRLSPLHSVYVDQWDWERVMGDGERQFSTLKSTVEAIWAGIKATEAAVSEEFGLAPFLPDQIHFVHSQELLSRYPDLDAKGRERAIAKDLGAVFLVGIGGKLSDGHRHDVRAPDYDDWSTPSELGHAGLNGDILVWNPVLEDAFELSSMGIRVDADTLKHQLALTGDEDRLELEWHQALLRGEMPQTIGGGIGQSRLTMLLLQLPHIGQVQAGVWPAAVRESVPSLL',
      dnaSequence: 'ATGAAGACAGCTTACATCGCCAAACAGCGGCAGATCTCCGTTAAATCCCAACATTTCTCCCGGCAGCTGGAGGAGCGACTGGGCCTGATCGAGGTGCAGGCCCCCATCCTGTCCCGAGTGGGCGACGGGACCCAGGACAACCTGTCCGGCGCCGAGAAGGCCGTGCAGGTGAAGGTGAAGGCCCTGCCTGACGCCCAGTTTGAGGTGGTGCACTCGCTGGCCAAGTGGAAGCAGACACTGGGGCAGCATGACTTCAGCGCCGGCGAGGGGCTGTACACCCACATGAAGGCCCTGCGCCCCGACGAGGACCGACTGTCGCCGCTGCACTCGGTGTACGTGGACCAGTGGAACTGGGAGCGAGTGATGGGCGACGGCGAGCGGCAGTTCTCGACACTGAAGTCGACCGTCGAGGCCATCTGGGCCGGCATCAAGGCCACCGAGGCCGCCGTGTCGGAGGAGTTTGGGCTGGCCCCGTTTCTGCCTGACCAGATCCACTTCGTGCACTCGCAGGAGCTGCTGTCCCGCTACCCCGACCTGGACGCCAAGGGCCGCGAGCGAGCCATCGCCAAGGACCTGGGCGCCGTGTTCCTGGTGGGCATCGGCGGCAAACTGTCGGACGGCCACCGGCACGACGTGCGCGCCCCCGACTACGACGACTGGTCGACCCCGTCGGAGCTGGGCCACGCCGGCCTGAACGGGGACATCCTGGTGTGGAACCCGGTGCTGGAGGACGCCGTTGAGCTGTCGTCGATGGGCATCCGCGTGGACGCCGACACACTGAAGCACCAGCTGGCCCTGACCGGCGACGAGGACCGACTGGAGCTGGAGTGGCACCAGGCCCTGCTGCGCGGCGAGATGCCTCAGACCATCGGCGGCGGCATCGGCGGCAGTCGCCGCACCATGCTGCTGCTGCAGCTGCCCCACATCGGCGGCAGGTGCAGGCCGGCGTGTGGCCGGCCGCCGTGCGCGAGTCGGTGCCGTCGCTGCTG',
      mutations: ['V600E', 'L858R'],
      domains: ['Extracellular Domain', 'Transmembrane Domain', 'Intracellular Domain'],
    },
    biomarkerData: {
      expressionLevels: [
        { tissue: 'Bladder', level: 85, status: 'high' },
        { tissue: 'Lung', level: 72, status: 'high' },
        { tissue: 'Pancreas', level: 68, status: 'moderate' },
        { tissue: 'Liver', level: 45, status: 'low' },
      ],
      patientStratification: {
        highExpressors: 45,
        moderateExpressors: 35,
        lowExpressors: 20,
      },
      predictiveMarkers: ['PD-L1', 'TMB', 'MSI-H'],
    },
  },
  {
    id: 'lantheus',
    name: 'Lantheus',
    ticker: 'LNTH',
    assetName: 'Pylarify',
    isPrivate: false,
    mechanism: 'Radioligand',
    target: 'PSMA',
    stage: 'Commercial',
    marketCap: 3.8,
    valuation: 3.8,
    nextMilestone: 'EU expansion - Q3 2025',
    validationScore: 92,
    partnership: 'Novartis',
    structure: {
      ligand: 'PSMA-617',
      chelator: 'DOTA',
      isotope: 'Lu-177',
      halflife: '6.7 days',
    },
  },
  {
    id: 'stealth-bio',
    name: 'Stealth Bio',
    ticker: undefined,
    assetName: 'SB-001',
    isPrivate: true,
    mechanism: 'Gene Therapy',
    target: 'DMD',
    stage: 'Series A',
    totalRaised: 45,
    valuation: 0.12,
    leadInvestor: 'Flagship Pioneering',
    nextMilestone: 'IND filing - Q4 2025',
    validationScore: 65,
    backers: ['Flagship Pioneering', 'Third Rock Ventures'],
    structure: {
      vector: 'AAV9',
      promoter: 'CMV',
      transgene: 'DMD-Micro',
      route: 'IT',
    },
  },
];
