import { Company } from './types';

export const companies: Company[] = [
  {
    id: 'bicycle-therapeutics',
    name: 'Bicycle Therapeutics',
    ticker: 'BCYC',
    assetName: 'BT8009',
    isPrivate: false,
    mechanism: 'ADC',
    target: 'Nectin-4',
    stage: 'Phase 2',
    marketCap: 1.2,
    valuation: 1.2,
    nextMilestone: 'Phase 2 data readout - Q2 2025',
    validationScore: 78,
    backers: ['Atlas Venture', 'Novartis Ventures'],
    targetBiology: 'Nectin-4 is a cell adhesion molecule that plays a critical role in cell-cell interactions, particularly in epithelial tissues. It is overexpressed in various cancer types including bladder, lung, and pancreatic cancers, making it an attractive therapeutic target. The protein\'s extracellular domain mediates binding to its ligands, while its intracellular domain interacts with signaling pathways that promote cell survival and proliferation.',
    discoveryTimeline: [
      { date: '1995', event: 'Initial identification in cell adhesion studies' },
      { date: '2003', event: 'Role in cancer progression established' },
      { date: '2010', event: 'First therapeutic targeting attempts' },
      { date: '2018', event: 'Clinical validation in multiple indications' },
    ],
    structure: {
      type: 'Peptide',
      linker: 'Val-Cit',
      payload: 'MMAE',
      dar: 4,
    },
    geneticEvidence: [
      { text: 'Knockout studies show reduced tumor growth', status: 'strong', source: 'PubMed' },
      { text: 'GWAS association with disease risk', status: 'moderate', source: 'Nature Genetics' },
    ],
    clinicalPrecedent: [
      { text: 'Similar targets show clinical efficacy', status: 'strong', source: 'FDA' },
      { text: 'Phase 2 data from competitor programs', status: 'moderate', source: 'ClinicalTrials.gov' },
    ],
    biologicalRationale: [
      { text: 'Target expression correlates with patient outcomes', status: 'strong', source: 'PubMed' },
      { text: 'Mechanism of action well-characterized', status: 'strong', source: 'Cell' },
      { text: 'Limited off-target effects in preclinical models', status: 'moderate', source: 'ToxSci' },
    ],
    safetyData: {
      risks: [
        { organ: 'skin', level: 'high', notes: 'High expression in keratinocytes' },
        { organ: 'liver', level: 'medium', notes: 'Metabolic clearance pathway' },
        { organ: 'kidneys', level: 'low', notes: 'Minimal renal excretion' },
        { organ: 'lungs', level: 'medium', notes: 'Moderate target expression' },
        { organ: 'stomach', level: 'low', notes: 'Low target expression' },
        { organ: 'smallIntestine', level: 'medium', notes: 'GI tract exposure' },
        { organ: 'largeIntestine', level: 'low', notes: 'Minimal absorption' },
        { organ: 'bladder', level: 'low', notes: 'Renal clearance' },
      ],
      aeTable: [
        { event: 'Rash', allGrade: 45, grade3_4: 8, related: 'Target', comparator: 12 },
        { event: 'Fatigue', allGrade: 38, grade3_4: 5, related: 'Both', comparator: 35 },
        { event: 'Nausea', allGrade: 32, grade3_4: 3, related: 'Payload', comparator: 28 },
        { event: 'Neutropenia', allGrade: 25, grade3_4: 12, related: 'Payload', comparator: 18 },
        { event: 'Peripheral Neuropathy', allGrade: 18, grade3_4: 4, related: 'Payload', comparator: 15 },
      ],
    },
    validationMetrics: [
      {
        category: 'Genetic Evidence',
        score: 85,
        maxScore: 100,
        status: 'strong',
        details: ['Knockout studies show reduced tumor growth', 'GWAS association with disease risk'],
      },
      {
        category: 'Clinical Precedent',
        score: 78,
        maxScore: 100,
        status: 'strong',
        details: ['Similar targets show clinical efficacy', 'Phase 2 data from competitor programs'],
      },
      {
        category: 'Biological Rationale',
        score: 82,
        maxScore: 100,
        status: 'strong',
        details: ['Target expression correlates with patient outcomes', 'Mechanism of action well-characterized'],
      },
      {
        category: 'Safety Profile',
        score: 65,
        maxScore: 100,
        status: 'moderate',
        details: ['Manageable toxicity profile', 'Some organ-specific risks identified'],
      },
    ],
    sequenceData: {
      proteinSequence: 'MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEKAVQVKVKALPDAQFEVVHSLAKWKRQTLGQHDFSAGEGLYTHMKALRPDEDRLSPLHSVYVDQWDWERVMGDGERQFSTLKSTVEAIWAGIKATEAAVSEEFGLAPFLPDQIHFVHSQELLSRYPDLDAKGRERAIAKDLGAVFLVGIGGKLSDGHRHDVRAPDYDDWSTPSELGHAGLNGDILVWNPVLEDAFELSSMGIRVDADTLKHQLALTGDEDRLELEWHQALLRGEMPQTIGGGIGQSRLTMLLLQLPHIGQVQAGVWPAAVRESVPSLL',
      dnaSequence: 'ATGAAGACAGCTTACATCGCCAAACAGCGGCAGATCTCCGTTAAATCCCAACATTTCTCCCGGCAGCTGGAGGAGCGACTGGGCCTGATCGAGGTGCAGGCCCCCATCCTGTCCCGAGTGGGCGACGGGACCCAGGACAACCTGTCCGGCGCCGAGAAGGCCGTGCAGGTGAAGGTGAAGGCCCTGCCTGACGCCCAGTTTGAGGTGGTGCACTCGCTGGCCAAGTGGAAGCAGACACTGGGGCAGCATGACTTCAGCGCCGGCGAGGGGCTGTACACCCACATGAAGGCCCTGCGCCCCGACGAGGACCGACTGTCGCCGCTGCACTCGGTGTACGTGGACCAGTGGAACTGGGAGCGAGTGATGGGCGACGGCGAGCGGCAGTTCTCGACACTGAAGTCGACCGTCGAGGCCATCTGGGCCGGCATCAAGGCCACCGAGGCCGCCGTGTCGGAGGAGTTTGGGCTGGCCCCGTTTCTGCCTGACCAGATCCACTTCGTGCACTCGCAGGAGCTGCTGTCCCGCTACCCCGACCTGGACGCCAAGGGCCGCGAGCGAGCCATCGCCAAGGACCTGGGCGCCGTGTTCCTGGTGGGCATCGGCGGCAAACTGTCGGACGGCCACCGGCACGACGTGCGCGCCCCCGACTACGACGACTGGTCGACCCCGTCGGAGCTGGGCCACGCCGGCCTGAACGGGGACATCCTGGTGTGGAACCCGGTGCTGGAGGACGCCGTTGAGCTGTCGTCGATGGGCATCCGCGTGGACGCCGACACACTGAAGCACCAGCTGGCCCTGACCGGCGACGAGGACCGACTGGAGCTGGAGTGGCACCAGGCCCTGCTGCGCGGCGAGATGCCTCAGACCATCGGCGGCGGCATCGGCGGCAGTCGCCGCACCATGCTGCTGCTGCAGCTGCCCCACATCGGCGGCAGGTGCAGGCCGGCGTGTGGCCGGCCGCCGTGCGCGAGTCGGTGCCGTCGCTGCTG',
      mutations: ['V600E', 'L858R'],
      domains: ['Extracellular Domain', 'Transmembrane Domain', 'Intracellular Domain'],
    },
    biomarkerData: {
      expressionLevels: [
        { tissue: 'Bladder', level: 85, status: 'high' },
        { tissue: 'Lung', level: 72, status: 'high' },
        { tissue: 'Pancreas', level: 68, status: 'moderate' },
        { tissue: 'Liver', level: 45, status: 'low' },
      ],
      patientStratification: {
        highExpressors: 45,
        moderateExpressors: 35,
        lowExpressors: 20,
      },
      predictiveMarkers: ['PD-L1', 'TMB', 'MSI-H'],
    },
    // NEW FIELDS FOR HOME PAGE
    scores: {
      validation: 78,
      safety: 65,
      ip: 42,
    },
    trend: {
      value: 78,
      change: 3,
      direction: 'up',
      sparkline: [65, 68, 70, 72, 71, 73, 75, 74, 76, 78, 77, 79, 80, 78, 76, 77, 78, 79, 80, 81, 79, 78, 77, 78, 79, 80, 78, 77, 78, 78],
    },
    aiInsight: {
      summary: 'Better safety profile vs Padcev. Watch skin toxicity signals in upcoming data.',
      confidence: 'high',
      generatedAt: '2024-12-01T10:00:00Z',
    },
    status: 'new',
    alerts: [
      { type: 'safety', message: '2 new safety signals', severity: 'medium', date: '2024-12-01' },
    ],
    lastUpdated: '2024-12-01T10:00:00Z',
    isWatchlisted: true,
  },
  {
    id: 'lantheus',
    name: 'Lantheus Holdings',
    ticker: 'LNTH',
    assetName: 'PNT2002',
    isPrivate: false,
    mechanism: 'Radioligand',
    target: 'PSMA',
    stage: 'Phase 2',
    marketCap: 4.8,
    valuation: 4.8,
    nextMilestone: 'EU expansion - Q3 2025',
    validationScore: 92,
    partnership: 'Novartis',
    structure: {
      ligand: 'PSMA-617',
      chelator: 'DOTA',
      isotope: 'Lu-177',
      halflife: '6.7 days',
    },
    // NEW FIELDS FOR HOME PAGE
    scores: {
      validation: 92,
      safety: 88,
      ip: 71,
    },
    trend: {
      value: 92,
      change: 1,
      direction: 'up',
      sparkline: [85, 86, 87, 88, 89, 90, 89, 90, 91, 90, 91, 92, 91, 92, 93, 92, 91, 92, 93, 92, 91, 92, 91, 92, 93, 92, 91, 92, 92, 92],
    },
    aiInsight: {
      summary: 'Strong validation from Pluvicto precedent. Differentiated dosing may improve therapeutic window.',
      confidence: 'high',
      generatedAt: '2024-11-30T08:00:00Z',
    },
    status: 'watching',
    alerts: [],
    lastUpdated: '2024-11-30T08:00:00Z',
    isWatchlisted: true,
  },
  {
    id: 'stealth-bio',
    name: 'Stealth BioTherapeutics',
    ticker: 'MITO',
    assetName: 'SBT-272',
    isPrivate: false,
    mechanism: 'Gene Therapy',
    target: 'DMD',
    stage: 'Phase 1',
    marketCap: 0.18,
    valuation: 0.18,
    totalRaised: 45,
    leadInvestor: 'Flagship Pioneering',
    nextMilestone: 'IND filing - Q4 2025',
    validationScore: 65,
    backers: ['Flagship Pioneering', 'Third Rock Ventures'],
    structure: {
      vector: 'AAV9',
      promoter: 'CMV',
      transgene: 'DMD-Micro',
      route: 'IT',
    },
    // NEW FIELDS FOR HOME PAGE
    scores: {
      validation: 65,
      safety: 72,
      ip: 38,
    },
    trend: {
      value: 65,
      change: -2,
      direction: 'down',
      sparkline: [70, 69, 68, 69, 68, 67, 68, 67, 66, 67, 66, 65, 66, 65, 64, 65, 66, 65, 64, 65, 66, 65, 64, 65, 66, 65, 64, 65, 65, 65],
    },
    aiInsight: {
      summary: 'Novel mechanism but limited clinical validation. IP landscape crowded - FTO risk.',
      confidence: 'medium',
      generatedAt: '2024-11-27T12:00:00Z',
    },
    status: 'review',
    alerts: [
      { type: 'ip', message: 'IP overlap with Sarepta', severity: 'high', date: '2024-11-27' },
    ],
    lastUpdated: '2024-11-27T12:00:00Z',
    isWatchlisted: false,
  },
  {
    id: 'immunocore',
    name: 'Immunocore',
    ticker: 'IMCR',
    assetName: 'IMC-F106C',
    isPrivate: false,
    mechanism: 'TCR Bispecific',
    target: 'PRAME',
    stage: 'Phase 2',
    marketCap: 2.1,
    valuation: 2.1,
    validationScore: 81,
    // NEW FIELDS FOR HOME PAGE
    scores: {
      validation: 81,
      safety: 70,
      ip: 85,
    },
    trend: {
      value: 81,
      change: 5,
      direction: 'up',
      sparkline: [70, 72, 71, 73, 74, 75, 74, 76, 77, 78, 77, 79, 80, 79, 78, 79, 80, 81, 80, 79, 80, 81, 82, 81, 80, 81, 82, 81, 81, 81],
    },
    aiInsight: {
      summary: 'Kimmtrak success validates platform. PRAME expression broader than expected.',
      confidence: 'high',
      generatedAt: '2024-12-01T06:00:00Z',
    },
    status: 'new',
    alerts: [
      { type: 'catalyst', message: 'Positive interim readout', severity: 'high', date: '2024-12-01' },
    ],
    lastUpdated: '2024-12-01T06:00:00Z',
    isWatchlisted: false,
  },
  {
    id: 'replimune',
    name: 'Replimune',
    ticker: 'REPL',
    assetName: 'RP1',
    isPrivate: false,
    mechanism: 'Oncolytic Virus',
    target: 'HSV',
    stage: 'Phase 2',
    marketCap: 0.89,
    valuation: 0.89,
    validationScore: 58,
    // NEW FIELDS FOR HOME PAGE
    scores: {
      validation: 58,
      safety: 82,
      ip: 67,
    },
    trend: {
      value: 58,
      change: 0,
      direction: 'stable',
      sparkline: [58, 59, 58, 57, 58, 59, 58, 57, 58, 59, 58, 57, 58, 59, 58, 57, 58, 59, 58, 57, 58, 59, 58, 57, 58, 59, 58, 57, 58, 58],
    },
    aiInsight: {
      summary: 'Combination potential with checkpoint inhibitors. Monotherapy data underwhelming.',
      confidence: 'medium',
      generatedAt: '2024-11-15T10:00:00Z',
    },
    status: 'stale',
    alerts: [],
    lastUpdated: '2024-11-15T10:00:00Z',
    isWatchlisted: false,
  },
];
