/**
 * Professional PDF Generator for Investment Memos
 *
 * Creates institutional-grade PDFs suitable for IC presentations
 * Uses puppeteer + marked for proper markdown rendering
 */

import { marked } from 'marked';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import { ExtractedSection } from './types';

export interface PDFGeneratorOptions {
  companyName?: string;
  analysisId?: string;
  generatedBy?: string;
  generatedAt: string;
  totalWords: number;
  totalPages: number;
}

// Configure marked for GitHub Flavored Markdown
marked.setOptions({
  gfm: true,
  breaks: true,
});

/**
 * Clean markdown content - remove cost displays and fix symbols
 */
function cleanMarkdown(markdown: string): string {
  return markdown
    .replace(/Cost estimate:?\s*\$[\d.]+/gi, '')
    .replace(/Analysis (cost|completed).*?\$[\d.]+/gi, '')
    .replace(/Total cost:?\s*\$[\d.]+/gi, '')
    .replace(/\$\d+\.\d{4}/g, '')
    .replace(/• '/g, '✓')
    .replace(/▌/g, '★')
    .trim();
}

/**
 * Generate professional investment memo PDF
 */
export async function generateInvestmentMemoPDF(
  sections: Record<string, ExtractedSection>,
  metadata: PDFGeneratorOptions
): Promise<Blob> {
  const date = new Date(metadata.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Build markdown content
  let markdownContent = '';

  // Table of contents
  markdownContent += '## TABLE OF CONTENTS\n\n';
  Object.values(sections).forEach((section, index) => {
    markdownContent += `${index + 1}. ${section.title}\n`;
  });
  markdownContent += '\n---\n\n';

  // Sections
  Object.values(sections).forEach((section, index) => {
    markdownContent += `## ${index + 1}. ${section.title.toUpperCase()}\n\n`;
    markdownContent += section.content;
    markdownContent += '\n\n---\n\n';
  });

  // Appendix
  markdownContent += '## APPENDIX: DOCUMENT METADATA\n\n';
  markdownContent += '| Field | Value |\n';
  markdownContent += '|-------|-------|\n';
  markdownContent += `| Analysis ID | ${metadata.analysisId || 'N/A'} |\n`;
  markdownContent += `| Company Name | ${metadata.companyName || 'N/A'} |\n`;
  markdownContent += `| Generated Date | ${date} |\n`;
  markdownContent += `| Generated By | ${metadata.generatedBy || 'AI Agent System'} |\n`;
  markdownContent += `| Total Word Count | ${metadata.totalWords.toLocaleString()} |\n`;
  markdownContent += `| Number of Sections | ${Object.keys(sections).length} |\n`;

  // Clean and parse markdown to HTML
  const cleanedMarkdown = cleanMarkdown(markdownContent);
  const htmlContent = await marked.parse(cleanedMarkdown);

  // Build complete HTML document
  const htmlDocument = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Investment Memo - ${metadata.companyName || 'Analysis'}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      font-size: 11pt;
      line-height: 1.7;
      color: #1f2937;
      background: white;
    }

    .cover-page {
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
      color: white;
      page-break-after: always;
      position: relative;
    }

    .cover-page h1 {
      font-size: 48pt;
      font-weight: 700;
      margin-bottom: 32px;
      letter-spacing: -0.02em;
    }

    .cover-page h2 {
      font-size: 32pt;
      font-weight: 400;
      margin-bottom: 48px;
      opacity: 0.95;
    }

    .cover-page .meta {
      font-size: 14pt;
      opacity: 0.9;
      text-align: center;
      line-height: 2;
    }

    .cover-page .footer {
      position: absolute;
      bottom: 60px;
      left: 60px;
      right: 60px;
      text-align: center;
      font-size: 10pt;
      opacity: 0.8;
      padding: 20px;
      background: rgba(255, 255, 255, 0.1);
      border-radius: 8px;
    }

    .content {
      padding: 0.75in;
      max-width: 8.5in;
    }

    h1, h2, h3, h4, h5, h6 {
      font-weight: 600;
      color: #1e40af;
      margin-top: 32px;
      margin-bottom: 16px;
      line-height: 1.3;
    }

    h1 { font-size: 24pt; }
    h2 { font-size: 18pt; }
    h3 { font-size: 14pt; }

    p {
      margin-bottom: 12px;
      text-align: justify;
    }

    ul, ol {
      margin: 16px 0;
      padding-left: 24px;
    }

    li {
      margin-bottom: 8px;
      line-height: 1.7;
    }

    strong {
      font-weight: 600;
      color: #1f2937;
    }

    em {
      font-style: italic;
      color: #4b5563;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 24px 0;
      font-size: 10pt;
      page-break-inside: avoid;
    }

    thead {
      background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
      color: white;
    }

    th {
      padding: 12px;
      text-align: left;
      font-weight: 600;
      border: 1px solid #2563eb;
    }

    td {
      padding: 10px 12px;
      border: 1px solid #e5e7eb;
    }

    tbody tr:nth-child(even) {
      background-color: #f9fafb;
    }

    tbody tr:hover {
      background-color: #f3f4f6;
    }

    hr {
      border: none;
      border-top: 2px solid #e5e7eb;
      margin: 32px 0;
      page-break-after: avoid;
    }

    .page-break {
      page-break-before: always;
    }

    @media print {
      .cover-page {
        page-break-after: always;
      }

      h1, h2, h3, h4, h5, h6 {
        page-break-after: avoid;
      }

      table, figure, img {
        page-break-inside: avoid;
      }

      ul, ol {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="cover-page">
    <h1>INVESTMENT MEMO</h1>
    ${metadata.companyName ? `<h2>${metadata.companyName}</h2>` : ''}
    <div class="meta">
      <div>Generated: ${date}</div>
      ${metadata.generatedBy ? `<div>Prepared by: ${metadata.generatedBy}</div>` : ''}
    </div>
    <div class="footer">
      <strong>CONFIDENTIAL:</strong> This document contains proprietary information and is intended solely
      for the use of the designated recipient(s). Unauthorized distribution or disclosure is prohibited.
    </div>
  </div>

  <div class="content">
    ${htmlContent}
  </div>
</body>
</html>
  `;

  // Generate PDF using puppeteer
  let browser;
  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: true,
    });

    const page = await browser.newPage();
    await page.setContent(htmlDocument, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'Letter',
      printBackground: true,
      margin: {
        top: '0.5in',
        right: '0.75in',
        bottom: '0.5in',
        left: '0.75in'
      }
    });

    await browser.close();

    return new Blob([Buffer.from(pdfBuffer)], { type: 'application/pdf' });
  } catch (error) {
    if (browser) {
      await browser.close();
    }
    throw error;
  }
}

/**
 * Generate markdown export (alternative to PDF)
 */
export function generateInvestmentMemoMarkdown(
  sections: Record<string, ExtractedSection>,
  metadata: PDFGeneratorOptions
): string {
  const date = new Date(metadata.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let markdown = `# INVESTMENT MEMO\n\n`;

  if (metadata.companyName) {
    markdown += `## ${metadata.companyName}\n\n`;
  }

  markdown += `**Generated:** ${date}\n`;
  if (metadata.generatedBy) {
    markdown += `**Prepared by:** ${metadata.generatedBy}\n`;
  }
  markdown += `**Word Count:** ${metadata.totalWords.toLocaleString()}\n\n`;

  markdown += `---\n\n`;
  markdown += `*CONFIDENTIAL: This document contains proprietary information and is intended solely for the use of the designated recipient(s).*\n\n`;
  markdown += `---\n\n`;

  // Table of Contents
  markdown += `## TABLE OF CONTENTS\n\n`;
  Object.values(sections).forEach((section, index) => {
    markdown += `${index + 1}. ${section.title}\n`;
  });
  markdown += `\n---\n\n`;

  // Sections
  Object.values(sections).forEach((section, index) => {
    markdown += `## ${index + 1}. ${section.title.toUpperCase()}\n\n`;
    markdown += section.content;
    markdown += `\n\n---\n\n`;
  });

  // Metadata
  markdown += `## APPENDIX: DOCUMENT METADATA\n\n`;
  markdown += `| Field | Value |\n`;
  markdown += `|-------|-------|\n`;
  markdown += `| Analysis ID | ${metadata.analysisId || 'N/A'} |\n`;
  markdown += `| Company Name | ${metadata.companyName || 'N/A'} |\n`;
  markdown += `| Generated Date | ${date} |\n`;
  markdown += `| Generated By | ${metadata.generatedBy || 'AI Agent System'} |\n`;
  markdown += `| Total Word Count | ${metadata.totalWords.toLocaleString()} |\n`;
  markdown += `| Number of Sections | ${Object.keys(sections).length} |\n`;

  return markdown;
}
