/**
 * Professional PDF Generator for Investment Memos
 *
 * Creates institutional-grade PDFs suitable for IC presentations
 * Uses puppeteer + marked for proper markdown rendering
 */

import { marked } from 'marked';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import { ExtractedSection } from './types';

export interface PDFGeneratorOptions {
  companyName?: string;
  analysisId?: string;
  generatedBy?: string;
  generatedAt: string;
  totalWords: number;
  totalPages: number;
}

// Configure marked for GitHub Flavored Markdown
marked.setOptions({
  gfm: true,
  breaks: true,
});

/**
 * Clean markdown content - remove cost displays and fix symbols
 */
function cleanMarkdown(markdown: string): string {
  return markdown
    .replace(/Cost estimate:?\s*\$[\d.]+/gi, '')
    .replace(/Analysis (cost|completed).*?\$[\d.]+/gi, '')
    .replace(/Total cost:?\s*\$[\d.]+/gi, '')
    .replace(/\$\d+\.\d{4}/g, '')
    .replace(/• '/g, '✓')
    .replace(/▌/g, '★')
    .trim();
}

/**
 * Generate professional investment memo PDF
 */
export async function generateInvestmentMemoPDF(
  sections: Record<string, ExtractedSection>,
  metadata: PDFGeneratorOptions
): Promise<Blob> {
  const date = new Date(metadata.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Build markdown content
  let markdownContent = '';

  // Table of contents
  markdownContent += '## TABLE OF CONTENTS\n\n';
  Object.values(sections).forEach((section, index) => {
    markdownContent += `${index + 1}. ${section.title}\n`;
  });
  markdownContent += '\n---\n\n';

  // Sections
  Object.values(sections).forEach((section, index) => {
    markdownContent += `## ${index + 1}. ${section.title.toUpperCase()}\n\n`;
    markdownContent += section.content;
    markdownContent += '\n\n---\n\n';
  });

  // Appendix
  markdownContent += '## APPENDIX: DOCUMENT METADATA\n\n';
  markdownContent += '| Field | Value |\n';
  markdownContent += '|-------|-------|\n';
  markdownContent += `| Analysis ID | ${metadata.analysisId || 'N/A'} |\n`;
  markdownContent += `| Company Name | ${metadata.companyName || 'N/A'} |\n`;
  markdownContent += `| Generated Date | ${date} |\n`;
  markdownContent += `| Generated By | ${metadata.generatedBy || 'AI Agent System'} |\n`;
  markdownContent += `| Total Word Count | ${metadata.totalWords.toLocaleString()} |\n`;
  markdownContent += `| Number of Sections | ${Object.keys(sections).length} |\n`;

  // Clean and parse markdown to HTML
  const cleanedMarkdown = cleanMarkdown(markdownContent);
  const htmlContent = await marked.parse(cleanedMarkdown);

  // Build complete HTML document with quiet luxury design
  const htmlDocument = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Investment Memorandum - ${metadata.companyName || 'Analysis'}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Helvetica+Neue:wght@300;400;500&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
      font-size: 11pt;
      font-weight: 300;
      line-height: 1.6;
      color: #2C2C2C;
      background: #FAF9F6;
    }

    /* Quiet Luxury Cover Page */
    .cover-page {
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background: #FAF9F6;
      color: #1B2B3A;
      page-break-after: always;
      position: relative;
      padding: 1.5in;
    }

    .cover-page h1 {
      font-family: 'EB Garamond', 'Garamond', 'Georgia', serif;
      font-size: 36pt;
      font-weight: 400;
      margin-bottom: 0.5in;
      letter-spacing: 0.02em;
      text-align: center;
      color: #1B2B3A;
    }

    .cover-page h2 {
      font-family: 'EB Garamond', 'Garamond', 'Georgia', serif;
      font-size: 18pt;
      font-weight: 400;
      margin-bottom: 0.5in;
      color: #2C2C2C;
      text-align: center;
    }

    .cover-page .divider {
      width: 3in;
      height: 1pt;
      background: #B8956A;
      margin: 0.5in auto;
    }

    .cover-page .meta {
      font-size: 12pt;
      text-align: center;
      line-height: 1.8;
      color: #2C2C2C;
      margin-top: 0.5in;
    }

    .cover-page .footer {
      position: absolute;
      bottom: 1in;
      left: 1.25in;
      right: 1.25in;
      text-align: center;
      font-size: 8pt;
      font-weight: 300;
      color: #2C2C2C;
      line-height: 1.4;
    }

    .content {
      padding: 1.25in;
      max-width: 8.5in;
    }

    /* Typography - Quiet Luxury */
    h1, h2, h3, h4, h5, h6 {
      font-weight: 600;
      color: #1B2B3A;
      margin-top: 0.5in;
      margin-bottom: 16px;
      line-height: 1.3;
      page-break-after: avoid;
    }

    h1 {
      font-family: 'EB Garamond', 'Garamond', 'Georgia', serif;
      font-size: 18pt;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    h2 {
      font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
      font-size: 14pt;
      font-weight: 500;
    }

    h3 {
      font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
      font-size: 12pt;
      font-weight: 500;
    }

    p {
      margin-bottom: 12px;
      text-align: left;
      line-height: 1.6;
    }

    ul, ol {
      margin: 16px 0;
      padding-left: 24px;
    }

    li {
      margin-bottom: 8px;
      line-height: 1.6;
    }

    strong {
      font-weight: 500;
      color: #2C2C2C;
    }

    em {
      font-style: italic;
      color: #2C2C2C;
    }

    /* Tables - Navy Headers with White Text */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 24px 0;
      font-size: 10pt;
      page-break-inside: avoid;
    }

    thead {
      background: #1B2B3A;
      color: white;
    }

    th {
      padding: 8px 12px;
      text-align: left;
      font-weight: 500;
      font-size: 10pt;
      border: 1px solid #E5E5E5;
      color: white;
    }

    td {
      padding: 8px 12px;
      border: 1px solid #E5E5E5;
      vertical-align: top;
    }

    tbody tr:nth-child(even) {
      background-color: #F5F5F5;
    }

    tbody tr:nth-child(odd) {
      background-color: white;
    }

    hr {
      border: none;
      border-top: 1px solid #E5E5E5;
      margin: 0.5in 0;
      page-break-after: avoid;
    }

    .page-break {
      page-break-before: always;
    }

    /* Page numbering */
    @page {
      margin: 0.5in 1.25in;
      @bottom-right {
        content: counter(page);
        font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
        font-size: 9pt;
        font-weight: 300;
        color: #2C2C2C;
      }
    }

    @media print {
      .cover-page {
        page-break-after: always;
      }

      h1, h2, h3, h4, h5, h6 {
        page-break-after: avoid;
      }

      table, figure, img {
        page-break-inside: avoid;
      }

      ul, ol {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="cover-page">
    <h1>INVESTMENT MEMORANDUM</h1>
    ${metadata.companyName ? `<h2>${metadata.companyName}</h2>` : ''}
    <div class="divider"></div>
    <div class="meta">
      <div>Generated: ${date}</div>
      ${metadata.generatedBy ? `<div>Prepared by: ${metadata.generatedBy}</div>` : ''}
      <div style="margin-top: 0.3in;">Investment Committee</div>
    </div>
    <div class="footer">
      CONFIDENTIAL AND PROPRIETARY<br>
      This document contains proprietary information and is intended solely
      for the use of the designated recipient(s). Unauthorized distribution or disclosure is prohibited.
    </div>
  </div>

  <div class="content">
    ${htmlContent}
  </div>
</body>
</html>
  `;

  // Generate PDF using puppeteer
  let browser;
  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: true,
    });

    const page = await browser.newPage();
    await page.setContent(htmlDocument, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'Letter',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 9pt; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                    color: #2C2C2C; text-align: right; width: 100%; padding-right: 1.25in; margin-top: 0.25in;">
          <span class="pageNumber"></span>
        </div>
      `,
      margin: {
        top: '1.25in',
        right: '1.25in',
        bottom: '1.25in',
        left: '1.25in'
      }
    });

    await browser.close();

    return new Blob([Buffer.from(pdfBuffer)], { type: 'application/pdf' });
  } catch (error) {
    if (browser) {
      await browser.close();
    }
    throw error;
  }
}

/**
 * Generate markdown export (alternative to PDF) - Institutional format
 */
export function generateInvestmentMemoMarkdown(
  sections: Record<string, ExtractedSection>,
  metadata: PDFGeneratorOptions
): string {
  const date = new Date(metadata.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let markdown = `# INVESTMENT MEMORANDUM\n\n`;

  if (metadata.companyName) {
    markdown += `## ${metadata.companyName}\n\n`;
  }

  markdown += `---\n\n`;

  markdown += `**Generated:** ${date}\n`;
  if (metadata.generatedBy) {
    markdown += `**Prepared by:** ${metadata.generatedBy}\n`;
  }
  markdown += `**Investment Committee**\n\n`;

  markdown += `---\n\n`;
  markdown += `**CONFIDENTIAL AND PROPRIETARY**\n\n`;
  markdown += `*This document contains proprietary information and is intended solely for the use of the designated recipient(s). Unauthorized distribution or disclosure is prohibited.*\n\n`;
  markdown += `---\n\n`;

  // Table of Contents
  markdown += `## TABLE OF CONTENTS\n\n`;
  Object.values(sections).forEach((section, index) => {
    markdown += `${index + 1}. ${section.title}\n`;
  });
  markdown += `\n---\n\n`;

  // Sections
  Object.values(sections).forEach((section, index) => {
    markdown += `## ${index + 1}. ${section.title.toUpperCase()}\n\n`;
    markdown += section.content;
    markdown += `\n\n---\n\n`;
  });

  // Appendix
  markdown += `## APPENDIX A: DOCUMENT METADATA\n\n`;
  markdown += `| Field | Value |\n`;
  markdown += `|-------|-------|\n`;
  markdown += `| Analysis ID | ${metadata.analysisId || 'N/A'} |\n`;
  markdown += `| Company Name | ${metadata.companyName || 'N/A'} |\n`;
  markdown += `| Generated Date | ${date} |\n`;
  markdown += `| Generated By | ${metadata.generatedBy || 'Multi-Agent Analysis System'} |\n`;
  markdown += `| Total Word Count | ${metadata.totalWords.toLocaleString()} |\n`;
  markdown += `| Estimated Pages | ${metadata.totalPages} |\n`;
  markdown += `| Number of Sections | ${Object.keys(sections).length} |\n\n`;

  markdown += `---\n\n`;
  markdown += `*End of Investment Memorandum*\n`;

  return markdown;
}
