/**
 * Professional PDF Generator for Investment Memos
 *
 * Creates institutional-grade PDFs suitable for IC presentations
 * Uses puppeteer + marked for proper markdown rendering
 */

import { marked } from 'marked';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import { ExtractedSection } from './types';

export interface PDFGeneratorOptions {
  companyName?: string;
  analysisId?: string;
  generatedBy?: string;
  generatedAt: string;
  totalWords: number;
  totalPages: number;
}

// Configure marked for GitHub Flavored Markdown
marked.setOptions({
  gfm: true,
  breaks: true,
});

/**
 * Clean markdown content - remove cost displays and fix symbols
 */
function cleanMarkdown(markdown: string): string {
  return markdown
    .replace(/Cost estimate:?\s*\$[\d.]+/gi, '')
    .replace(/Analysis (cost|completed).*?\$[\d.]+/gi, '')
    .replace(/Total cost:?\s*\$[\d.]+/gi, '')
    .replace(/\$\d+\.\d{4}/g, '')
    .replace(/• '/g, '✓')
    .replace(/▌/g, '★')
    .trim();
}

/**
 * Generate professional investment memo PDF
 */
export async function generateInvestmentMemoPDF(
  sections: Record<string, ExtractedSection>,
  metadata: PDFGeneratorOptions
): Promise<Blob> {
  const date = new Date(metadata.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Build markdown content
  let markdownContent = '';

  // Table of contents
  markdownContent += '## TABLE OF CONTENTS\n\n';
  Object.values(sections).forEach((section, index) => {
    markdownContent += `${index + 1}. ${section.title}\n`;
  });
  markdownContent += '\n---\n\n';

  // Sections
  Object.values(sections).forEach((section, index) => {
    markdownContent += `## ${index + 1}. ${section.title.toUpperCase()}\n\n`;
    markdownContent += section.content;
    markdownContent += '\n\n---\n\n';
  });

  // Appendix
  markdownContent += '## APPENDIX: DOCUMENT METADATA\n\n';
  markdownContent += '| Field | Value |\n';
  markdownContent += '|-------|-------|\n';
  markdownContent += `| Analysis ID | ${metadata.analysisId || 'N/A'} |\n`;
  markdownContent += `| Company Name | ${metadata.companyName || 'N/A'} |\n`;
  markdownContent += `| Generated Date | ${date} |\n`;
  markdownContent += `| Generated By | ${metadata.generatedBy || 'AI Agent System'} |\n`;
  markdownContent += `| Total Word Count | ${metadata.totalWords.toLocaleString()} |\n`;
  markdownContent += `| Number of Sections | ${Object.keys(sections).length} |\n`;

  // Clean and parse markdown to HTML
  const cleanedMarkdown = cleanMarkdown(markdownContent);
  const htmlContent = await marked.parse(cleanedMarkdown);

  // Build complete HTML document with modern minimalist design
  const htmlDocument = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Investment Memorandum - ${metadata.companyName || 'Analysis'}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    @page {
      size: letter;
      margin: 0.75in;
    }

    body {
      font-family: Arial, sans-serif;
      font-size: 11pt;
      font-weight: 400;
      line-height: 1.6;
      color: #1E293B;
      background-color: white;
    }

    /* Modern Minimalist Cover Page */
    .cover-page {
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background: white;
      page-break-after: always;
      position: relative;
      padding: 1.5in;
    }

    .cover-page h1 {
      font-family: Arial, sans-serif;
      font-size: 48pt;
      font-weight: 700;
      margin-bottom: 0.5in;
      letter-spacing: 0.05em;
      text-align: center;
      color: #1E293B;
      line-height: 1.2;
    }

    .cover-page h2 {
      font-family: Arial, sans-serif;
      font-size: 18pt;
      font-weight: 400;
      margin-bottom: 0.5in;
      color: #64748B;
      text-align: center;
    }

    .cover-page .divider {
      width: 3in;
      height: 3px;
      background: linear-gradient(to right, #3B82F6, transparent);
      margin: 0.5in auto;
    }

    .cover-page .meta {
      font-size: 11pt;
      text-align: center;
      line-height: 1.8;
      color: #64748B;
      margin-top: 2em;
    }

    .cover-page .footer {
      position: absolute;
      bottom: 2em;
      left: 0;
      right: 0;
      padding: 1.5em;
      background-color: #F8FAFC;
      border-top: 2px solid #3B82F6;
      text-align: center;
      font-size: 9pt;
      font-weight: 400;
      color: #64748B;
      line-height: 1.4;
    }

    .content {
      padding: 0;
      max-width: 100%;
    }

    /* Typography - Modern Minimalist */
    h1, h2, h3, h4, h5, h6 {
      font-family: Arial, sans-serif;
      color: #1E293B;
      margin-top: 1.5em;
      margin-bottom: 1em;
      line-height: 1.3;
      page-break-after: avoid;
    }

    h1 {
      font-size: 24pt;
      font-weight: 700;
      color: #1E293B;
      border-bottom: 3px solid transparent;
      border-image: linear-gradient(to right, #3B82F6, transparent) 1;
      padding-bottom: 0.5em;
    }

    h2 {
      font-size: 18pt;
      font-weight: 700;
      color: #3B82F6;
    }

    h3 {
      font-size: 14pt;
      font-weight: 700;
      color: #3B82F6;
    }

    p {
      margin-bottom: 1.2em;
      text-align: left;
      line-height: 1.6;
      font-weight: 400;
    }

    ul, ol {
      margin: 1em 0;
      padding-left: 1.5em;
      list-style-type: none;
    }

    li {
      margin-bottom: 0.75em;
      line-height: 1.6;
      position: relative;
      padding-left: 1.5em;
      font-weight: 400;
    }

    li:before {
      content: "▸";
      color: #3B82F6;
      font-weight: bold;
      position: absolute;
      left: 0;
    }

    strong {
      font-weight: 700;
      color: inherit;
    }

    em {
      font-style: italic;
      color: inherit;
    }

    .highlight {
      color: #3B82F6;
      font-weight: 600;
    }

    /* Tables - Modern Minimalist with Accent Blue Headers */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1.5em 0;
      font-size: 10pt;
      page-break-inside: avoid;
    }

    thead {
      background-color: #3B82F6;
      color: white;
    }

    th {
      padding: 12px;
      text-align: left;
      font-weight: 600;
      font-size: 10pt;
      border-bottom: 2px solid #2563EB;
      color: white;
    }

    td {
      padding: 10px 12px;
      border-bottom: 1px solid #E2E8F0;
      vertical-align: top;
      font-weight: 400;
    }

    tbody tr:nth-child(even) {
      background-color: #F8FAFC;
    }

    tbody tr:nth-child(odd) {
      background-color: white;
    }

    /* Callout Boxes */
    .callout-box {
      background-color: #F8FAFC;
      border-left: 4px solid #3B82F6;
      padding: 1.5em;
      margin: 2em 0;
      border-radius: 4px;
      page-break-inside: avoid;
    }

    .callout-box h4 {
      margin-top: 0;
      margin-bottom: 0.75em;
      color: #3B82F6;
      font-weight: 600;
      font-size: 12pt;
    }

    hr {
      border: none;
      height: 3px;
      background: linear-gradient(to right, #3B82F6, transparent);
      margin: 0.5em 0 1.5em 0;
      page-break-after: avoid;
    }

    .page-break {
      page-break-before: always;
    }

    @media print {
      body {
        print-color-adjust: exact;
        -webkit-print-color-adjust: exact;
      }

      .cover-page {
        page-break-after: always;
      }

      h1, h2, h3, h4, h5, h6 {
        page-break-after: avoid;
      }

      table, figure, img, .callout-box {
        page-break-inside: avoid;
      }

      ul, ol {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="cover-page">
    <h1>INVESTMENT MEMORANDUM</h1>
    ${metadata.companyName ? `<h2>${metadata.companyName}</h2>` : ''}
    <div class="divider"></div>
    <div class="meta">
      <div>Generated: ${date}</div>
      ${metadata.generatedBy ? `<div>Prepared by: ${metadata.generatedBy}</div>` : ''}
      <div style="margin-top: 0.3in;">Investment Committee</div>
    </div>
    <div class="footer">
      CONFIDENTIAL AND PROPRIETARY<br>
      This document contains proprietary information and is intended solely
      for the use of the designated recipient(s). Unauthorized distribution or disclosure is prohibited.
    </div>
  </div>

  <div class="content">
    ${htmlContent}
  </div>
</body>
</html>
  `;

  // Generate PDF using puppeteer
  let browser;
  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: true,
    });

    const page = await browser.newPage();
    await page.setContent(htmlDocument, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'Letter',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 9pt; font-family: Arial, sans-serif; color: #64748B;
                    width: 100%; display: flex; justify-content: space-between; padding: 0 0.75in;">
          <span>Confidential Investment Memorandum</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
      margin: {
        top: '0.75in',
        right: '0.75in',
        bottom: '0.75in',
        left: '0.75in'
      },
      preferCSSPageSize: false
    });

    await browser.close();

    return new Blob([Buffer.from(pdfBuffer)], { type: 'application/pdf' });
  } catch (error) {
    if (browser) {
      await browser.close();
    }
    throw error;
  }
}

/**
 * Generate markdown export (alternative to PDF) - Institutional format
 */
export function generateInvestmentMemoMarkdown(
  sections: Record<string, ExtractedSection>,
  metadata: PDFGeneratorOptions
): string {
  const date = new Date(metadata.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let markdown = `# INVESTMENT MEMORANDUM\n\n`;

  if (metadata.companyName) {
    markdown += `## ${metadata.companyName}\n\n`;
  }

  markdown += `---\n\n`;

  markdown += `**Generated:** ${date}\n`;
  if (metadata.generatedBy) {
    markdown += `**Prepared by:** ${metadata.generatedBy}\n`;
  }
  markdown += `**Investment Committee**\n\n`;

  markdown += `---\n\n`;
  markdown += `**CONFIDENTIAL AND PROPRIETARY**\n\n`;
  markdown += `*This document contains proprietary information and is intended solely for the use of the designated recipient(s). Unauthorized distribution or disclosure is prohibited.*\n\n`;
  markdown += `---\n\n`;

  // Table of Contents
  markdown += `## TABLE OF CONTENTS\n\n`;
  Object.values(sections).forEach((section, index) => {
    markdown += `${index + 1}. ${section.title}\n`;
  });
  markdown += `\n---\n\n`;

  // Sections
  Object.values(sections).forEach((section, index) => {
    markdown += `## ${index + 1}. ${section.title.toUpperCase()}\n\n`;
    markdown += section.content;
    markdown += `\n\n---\n\n`;
  });

  // Appendix
  markdown += `## APPENDIX A: DOCUMENT METADATA\n\n`;
  markdown += `| Field | Value |\n`;
  markdown += `|-------|-------|\n`;
  markdown += `| Analysis ID | ${metadata.analysisId || 'N/A'} |\n`;
  markdown += `| Company Name | ${metadata.companyName || 'N/A'} |\n`;
  markdown += `| Generated Date | ${date} |\n`;
  markdown += `| Generated By | ${metadata.generatedBy || 'Multi-Agent Analysis System'} |\n`;
  markdown += `| Total Word Count | ${metadata.totalWords.toLocaleString()} |\n`;
  markdown += `| Estimated Pages | ${metadata.totalPages} |\n`;
  markdown += `| Number of Sections | ${Object.keys(sections).length} |\n\n`;

  markdown += `---\n\n`;
  markdown += `*End of Investment Memorandum*\n`;

  return markdown;
}
